env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  semi: [ 2, 'always' ],
  no-multiple-empty-lines: [ "error", { "max": 1, "maxEOF": 0 } ]

}
